{% set name = "openfe-analysis" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openfreeenergy/openfe_analysis/archive/{{ version }}.tar.gz
  sha256: 74afe903ef9e9095a59b48ee5e06a6f903d10cd693cb19ca2f0f3d7c8f2fe80e
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - versioningit
  run:
    - MDAnalysis
    - click
    - netCDF4
    - openff-units
    - python >=3.9

test:
  imports:
    - openfe_analysis
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/openfe_analysis
  summary: 'Analysis tools for the openfe ecosystem'
  description: |
    openfe-analysis is a set of analysis tools to check the 
    health of free energy calculations in the openfe ecosystem.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/OpenFreeEnergy/openfe_analysis
  dev_url: https://github.com/OpenFreeEnergy/openfe_analysis

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
